In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle as pkl

In [2]:
df = pd.read_csv('customer_churn_telecom_services.csv')

In [3]:
df.sample()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1338,Male,0,No,No,1,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.15,20.15,Yes

In [4]:
df[df['Churn'] =='Yes']

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
8,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
13,Male,0,No,No,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7021,Male,0,No,No,12,Yes,No,DSL,No,No,No,Yes,Yes,No,One year,Yes,Electronic check,59.80,727.80,Yes
7026,Female,0,No,No,9,Yes,No,DSL,No,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),44.20,403.35,Yes
7032,Male,1,No,No,1,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
7034,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [6]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [7]:
# DATA CLEANING

# DROP : DeviceProtection	TechSupport	StreamingTV	StreamingMovies  OnlineSecurity	OnlineBackup	DeviceProtection	TechSupport	
#

In [8]:
df1=df.drop(['DeviceProtection','TechSupport','StreamingTV','StreamingMovies','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','MultipleLines','PaperlessBilling'],axis=1)

In [9]:
df1.drop('gender',axis=1,inplace=True)

In [10]:
# PREPROCSSING

#  ONE HOT ENCODING : GENDER, DEPENDENTS , PHONESERVICE, INTERNETSERVICE, PATMENTMETHOD
#  ORDINAL ENCODING : PARNET , CONTRACT
#  LABEL ENCODING: CHURN

In [11]:
df['Churn'] =df['Churn'].apply(lambda x : 1 if x=='Yes' else 0 )

In [12]:
df1.sample(5)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn
6679,0,Yes,No,60,No,DSL,Two year,Bank transfer (automatic),37.70,2288.70,No
5089,0,Yes,Yes,8,Yes,DSL,Month-to-month,Electronic check,54.40,475.10,No
4724,0,Yes,Yes,50,Yes,DSL,One year,Bank transfer (automatic),80.05,4042.20,No
2655,0,No,Yes,4,Yes,Fiber optic,Month-to-month,Mailed check,89.60,365.65,Yes
876,0,No,No,15,Yes,Fiber optic,Month-to-month,Electronic check,105.10,1582.75,Yes

In [13]:
df1['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [14]:
df1['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [15]:
df1['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [17]:
x = df1.drop('Churn',axis=1)
y = df1['Churn']

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2 ,random_state=42)

In [19]:
dt = DecisionTreeClassifier(
    criterion='entropy',
    splitter='random',
    max_depth=10,
    min_samples_split = 5,
    max_features ='sqrt'
)
rfc = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features= 'sqrt'
)

In [20]:
transformer = ColumnTransformer(transformers=[
    ('ohe', OneHotEncoder(drop='first'),['Dependents' , 'PhoneService', 'InternetService', 'PaymentMethod']),
    ('ordinal', OrdinalEncoder(categories=[['Yes','No'],['Month-to-month','One year','Two year']]),['Partner','Contract']), 
],remainder='passthrough')

In [21]:
le = LabelEncoder()

In [43]:
y_train=le.fit_transform(y_train)

In [44]:
y_test = le.transform(y_test)

In [24]:
from sklearn.model_selection import GridSearchCV

In [45]:
params = {
    'criterion':['gini','Entropy'],
    'splitter':['Best','random'],
    'max_depth':[2,4,6,8,10,12] ,
    'min_samples_split' : [1,2,3,4,5,6,7],
    'max_features' : [2,3,4,'sqrt']
}
grid = GridSearchCV(dt,params,cv=5,scoring='accuracy')

In [46]:
params = {
        'n_estimators': [50, 100, 150],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt']
}
grid1 = GridSearchCV(rfc,params,cv=5,scoring='accuracy')

In [47]:
pipe = Pipeline([
    ('transformer',transformer),
    ('dtree',grid1)
])

In [48]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  ['Dependents', 'PhoneService',
                                                   'InternetService',
                                                   'PaymentMethod']),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['Yes',
                                                                              'No'],
                                                                             ['Month-to-month',
                                                                              'One '
                                                                              'year',
                                                                              'Two '
                                                                              'year']]),
                                                  ['Partner', 'Contract'])])),
                ('dtree',
                 GridSearchCV(cv=5,
                              estimator=RandomForestClassifier(max_depth=15,
                                                               min_samples_leaf=2,
                                                               min_samples_split=5,
                                                               n_estimators=200),
                              param_grid={'max_depth': [5, 10, None],
                                          'max_features': ['sqrt'],
                                          'min_samples_leaf': [1, 2],
                                          'min_samples_split': [2, 5],
                                          'n_estimators': [50, 100, 150]},
                              scoring='accuracy'))])

In [49]:
y_pred = pipe.predict(x_test)

In [50]:
accuracy_score(y_test,y_pred)

0.8055358410220014

In [52]:
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
print("ROC-AUC:", roc_auc_score(y_test, pipe.predict_proba(x_test)[:, 1]))

              precision    recall  f1-score   support

           0       0.83      0.93      0.88      1036
           1       0.70      0.47      0.56       373

    accuracy                           0.81      1409
   macro avg       0.76      0.70      0.72      1409
weighted avg       0.79      0.81      0.79      1409

[[961  75]
 [199 174]]
ROC-AUC: 0.8622084838572774

In [53]:
pipe1 = Pipeline([
    ('transform',transformer),
    ('grid',grid)
])

In [54]:
pipe1.fit(x_train,y_train)

D:\prtk\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
2640 fits failed out of a total of 3360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "D:\prtk\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prtk\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\prtk\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\prtk\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

--------------------------------------------------------------------------------
720 fits failed with the following error:
Traceback (most recent call last):
  File "D:\prtk\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prtk\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\prtk\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\prtk\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'splitter' parameter of DecisionTreeClassifier must be a str among {'random', 'best'}. Got 'Best' instead.

--------------------------------------------------------------------------------
1680 fits failed with the following error:
Traceback (most recent call last):
  File "D:\prtk\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prtk\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\prtk\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\prtk\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'entropy', 'gini', 'log_loss'}. Got 'Entropy' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
D:\prtk\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.73926077        nan 0.73730869
        nan 0.74405226        nan 0.7396157         nan 0.73446929
        nan 0.73588899        nan        nan        nan 0.7410354
        nan 0.74884374        nan 0.74085793        nan 0.75008976
        nan 0.74547195        nan 0.74565619        nan        nan
        nan 0.74848881        nan 0.75328329        nan 0.7461818
        nan 0.74227763        nan 0.75151135        nan 0.74654224
        nan        nan        nan 0.74387479        nan 0.74121459
        nan 0.74068047        nan 0.74032728        nan 0.7396157
        nan 0.74317093        nan        nan        nan 0.75452742
        nan 0.75505823        nan 0.76552582        nan 0.75861094
        nan 0.75097754        nan 0.75611969        nan        nan
        nan 0.75771953        nan 0.76872629        nan 0.76552976
        nan 0.77085473        nan 0.74653688        nan 0.76109652
        nan        nan        nan 0.7703244         nan 0.7712125
        nan 0.75843474        nan 0.77458507        nan 0.76855277
        nan 0.7641118         nan        nan        nan 0.76908185
        nan 0.76056176        nan 0.76996994        nan 0.77103614
        nan 0.76428895        nan 0.77032518        nan        nan
        nan 0.76127114        nan 0.761978          nan 0.77937434
        nan 0.76819548        nan 0.77600366        nan 0.76694852
        nan        nan        nan 0.78221279        nan 0.77387159
        nan 0.77422936        nan 0.77173984        nan 0.7813258
        nan 0.77617955        nan        nan        nan 0.77689129
        nan 0.77316521        nan 0.77528861        nan 0.77848798
        nan 0.77848703        nan 0.78257103        nan        nan
        nan 0.76766057        nan 0.7720965         nan 0.79109048
        nan 0.76286515        nan 0.77831036        nan 0.77493526
        nan        nan        nan 0.77777892        nan 0.7744043
        nan 0.7722738         nan 0.77085568        nan 0.77404921
        nan 0.77138933        nan        nan        nan 0.78221626
        nan 0.77547017        nan 0.77476048        nan 0.77830925
        nan 0.78043849        nan 0.78061831        nan        nan
        nan 0.78150436        nan 0.77422999        nan 0.78167946
        nan 0.7820347         nan 0.78043864        nan 0.77617892
        nan        nan        nan 0.78061863        nan 0.78132816
        nan 0.78257103        nan 0.77511698        nan 0.7784875
        nan 0.78221563        nan        nan        nan 0.76783772
        nan 0.77209713        nan 0.77405063        nan 0.77475859
        nan 0.77866465        nan 0.77653306        nan        nan
        nan 0.7763567         nan 0.77813116        nan 0.769082
        nan 0.76836884        nan 0.77955338        nan 0.78469884
        nan        nan        nan 0.76979138        nan 0.77848703
        nan 0.77689003        nan 0.78061658        nan 0.77582478
        nan 0.77174394        nan        nan        nan 0.77972943
        nan 0.7719203         nan 0.77493605        nan 0.77387254
        nan 0.77635622        nan 0.77511367        nan        nan
        nan 0.76251353        nan 0.76819579        nan 0.76677168
        nan 0.77032582        nan 0.76943456        nan 0.77547017
        nan        nan        nan 0.76907869        nan 0.76943441
        nan 0.76606136        nan 0.77600193        nan 0.77209681
        nan 0.76748295        nan        nan        nan 0.76109352
        nan 0.76641881        nan 0.76694899        nan 0.77138712
        nan 0.77458113        nan 0.76446436        nan        nan
        nan 0.76357531        nan 0.76765994        nan 0.76109194
        nan 0.77085521        nan 0.76695167        nan 0.77351683
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

Pipeline(steps=[('transform',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  ['Dependents', 'PhoneService',
                                                   'InternetService',
                                                   'PaymentMethod']),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['Yes',
                                                                              'No'],
                                                                             ['Month-to-month',
                                                                              'One '
                                                                              'year',
                                                                              'Two '
                                                                              'year']]),
                                                  ['Partner', 'Contract'])])),
                ('grid',
                 GridSearchCV(cv=5,
                              estimator=DecisionTreeClassifier(criterion='entropy',
                                                               max_depth=10,
                                                               max_features='sqrt',
                                                               min_samples_split=5,
                                                               splitter='random'),
                              param_grid={'criterion': ['gini', 'Entropy'],
                                          'max_depth': [2, 4, 6, 8, 10, 12],
                                          'max_features': [2, 3, 4, 'sqrt'],
                                          'min_samples_split': [1, 2, 3, 4, 5,
                                                                6, 7],
                                          'splitter': ['Best', 'random']},
                              scoring='accuracy'))])

In [60]:
y_pred1=pipe1.predict(x_test)

In [61]:
accuracy_score(y_test,y_pred1)

0.8090844570617459

In [62]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
print("ROC-AUC:", roc_auc_score(y_test, pipe1.predict_proba(x_test)[:, 1]))

              precision    recall  f1-score   support

           0       0.83      0.93      0.88      1036
           1       0.70      0.47      0.56       373

    accuracy                           0.81      1409
   macro avg       0.76      0.70      0.72      1409
weighted avg       0.79      0.81      0.79      1409

[[961  75]
 [199 174]]
ROC-AUC: 0.8440006935315246

In [73]:
df1.sample()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4369,0,No,No,3,No,DSL,Month-to-month,Electronic check,24.75,66.95,Yes

In [76]:
pipe.predict(pd.DataFrame([[0,'No','No',3,'No','DSL','Month-to-month','Electronic check',24.75,66.95]],columns=['SeniorCitizen','Partner','Dependents','tenure','PhoneService','InternetService','Contract','PaymentMethod','MonthlyCharges','TotalCharges']))[0]

np.int64(1)

In [65]:
pkl.dump(pipe, open('model.pkl','wb'))
df1.to_csv('df.csv')